### ISSUE TITLE
pulsar kop: kafka access pulsar:9092 failed

### ISSUE THREAD

**Issue by ChenJhua** [streamnative/charts#760]
镜像
```
[root@master-001 new]# docker images | grep stream
streamnative/sn-pulsar                                        2.9.2.12                                   e6136faa0338        2 months ago        3.87GB
streamnative/pulsar-all                                       2.9.2.12                                   b7f61294e736        2 months ago        3.51GB
streamnative/pulsar-manager                                   0.3.0                                      fb7162780ade        2 years ago         507MB
```
报错
```
I have no name!@kafka-client:/$ /opt/bitnami/kafka/bin/kafka-console-consumer.sh --bootstrap-server pulsar-kop-broker.pulsar-kop.svc.cluster.local:9092 --topic test --from-beginning
[2022-06-21 08:54:37,202] WARN [Consumer clientId=consumer-console-consumer-39637-1, groupId=console-consumer-39637] Error connecting to node pulsar-kop-broker-0.pulsar-kop.svc.cluster.local:9092 (id: 254478448 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: pulsar-kop-broker-0.pulsar-kop.svc.cluster.local: Name or service not known
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
	at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:110)
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:501)
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:458)
	at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:169)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1002)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:575)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:848)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:828)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:602)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:412)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:297)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:215)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:480)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1257)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1226)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1206)
	at kafka.tools.ConsoleConsumer$ConsumerWrapper.receive(ConsoleConsumer.scala:444)
	at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:103)
	at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:77)
	at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:54)
	at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
[2022-06-21 08:54:37,322] WARN [Consumer clientId=consumer-console-consumer-39637-1, groupId=console-consumer-39637] Error connecting to node pulsar-kop-broker-0.pulsar-kop.svc.cluster.local:9092 (id: 1893005199 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: pulsar-kop-broker-0.pulsar-kop.svc.cluster.local
```
配置
```
## disable pulsar-manager
initialize: true
components:
  autorecovery: false
  pulsar_manager: true
  kop: true
  control_center: false
  functions: false
  

## disable monitoring stack
monitoring:
  prometheus: false
  grafana: false
  node_exporter: true
  loki: false
  
zookeeper:
  replicaCount: 3
  volumes:
    data:
      storageClassName: local-storage
    
bookkeeper:
  replicaCount: 3
  volumes:
    journal:
      storageClassName: local-storage
    ledgers:
      storageClassName: local-storage

broker:
  replicaCount: 3
  annotations:
    sidecar.istio.io/inject: "true"

istio:
  enabled: true
  gateway:
    selector:
      istio: "ingressgateway"

ingress:
  kop: 
    enabled: true
    external_domain: pulsar-kop.svc.cluster.local
```
broker配置
```
packagesManagementStorageProvider=org.apache.pulsar.packages.management.storage.bookkeeper.BookKeeperPackagesStorageProvider
packagesReplicas=1
packagesManagementLedgerRootPath=/ledgers
brokerEntryMetadataInterceptors=org.apache.pulsar.common.intercept.AppendBrokerTimestampMetadataInterceptor,org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor
kafkaAdvertisedListeners=PLAINTEXT://pulsar-kop-broker-0.pulsar-kop.svc.cluster.local:9092
kafkaListeners=PLAINTEXT://pulsar-kop-broker-0.pulsar-kop-broker.pulsar-kop.svc.cluster.local:9092
messagingProtocols=kafka
```
运行情况
```
[root@master-001 cert]# kubectl get pods -n pulsar-kop
NAME                                   READY   STATUS      RESTARTS   AGE
pulsar-kop-alert-manager-0             2/2     Running     0          98m
pulsar-kop-bookie-0                    1/1     Running     0          98m
pulsar-kop-bookie-1                    1/1     Running     0          98m
pulsar-kop-bookie-2                    1/1     Running     0          98m
pulsar-kop-bookie-init-8m4sn           0/1     Completed   0          98m
pulsar-kop-broker-0                    1/1     Running     0          98m
pulsar-kop-broker-1                    1/1     Running     0          98m
pulsar-kop-broker-2                    1/1     Running     0          98m
pulsar-kop-node-exporter-mh2dx         1/1     Running     0          98m
pulsar-kop-node-exporter-p4ffk         1/1     Running     0          98m
pulsar-kop-node-exporter-qzbwk         1/1     Running     0          98m
pulsar-kop-proxy-0                     1/1     Running     0          98m
pulsar-kop-proxy-1                     1/1     Running     0          98m
pulsar-kop-proxy-2                     1/1     Running     0          98m
pulsar-kop-pulsar-init-cckss           0/1     Completed   0          98m
pulsar-kop-pulsar-manager-0            1/1     Running     0          98m
pulsar-kop-pulsar-manager-init-2wdkw   0/1     Completed   0          98m
pulsar-kop-toolset-0                   2/2     Running     0          98m
pulsar-kop-zookeeper-0                 1/1     Running     0          98m
pulsar-kop-zookeeper-1                 1/1     Running     0          97m
pulsar-kop-zookeeper-2                 1/1     Running     0          97m
```
When I don't use ingress, it will report an error that broker pods start failed: kafkaAdvertisedListeners, kafkaListeners cannot be found

**Comment by ericsyh** [comment]
@ChenJhua 我看了下感觉这部分 template 逻辑有点问题，我把这部分 [broker-statefulset.yaml#L330](https://github.com/streamnative/charts/blob/master/charts/pulsar/templates/broker/broker-statefulset.yaml#L330) 到 [broker-statefulset.yaml#L359](https://github.com/streamnative/charts/blob/master/charts/pulsar/templates/broker/broker-statefulset.yaml#L359) 简单改动了后能跑通

```
        {{- if and .Values.components.kop }}
        {{- if .Values.ingress.kop.enabled }}
        {{- if and .Values.tls.enabled .Values.tls.kop.enabled }}
        - name: PULSAR_PREFIX_kafkaAdvertisedListeners
          value: SSL://$(POD_NAME).{{ .Values.ingress.kop.external_domain }}:{{ .Values.kop.ports.ssl }}
        - name: PULSAR_PREFIX_kafkaListeners
          value: SSL://$(POD_NAME).{{ template "pulsar.broker.service.fqn" . }}:{{ .Values.kop.ports.ssl }}
        - name: PULSAR_PREFIX_kopSslKeystorePassword
          valueFrom:
            secretKeyRef:
              name: "{{ template "pulsar.fullname" . }}-{{ .Values.tls.proxy.cert_name }}-jks-passwd"
              key: password
        - name: PULSAR_PREFIX_kopSslKeyPassword
          valueFrom:
            secretKeyRef:
              name: "{{ template "pulsar.fullname" . }}-{{ .Values.tls.proxy.cert_name }}-jks-passwd"
              key: password
        - name: PULSAR_PREFIX_kopSslTruststorePassword
          valueFrom:
            secretKeyRef:
              name: "{{ template "pulsar.fullname" . }}-{{ .Values.tls.proxy.cert_name }}-jks-passwd"
              key: password
        {{- end }}
        {{- end }}
        - name: PULSAR_PREFIX_kafkaAdvertisedListeners
          value: PLAINTEXT://$(POD_NAME).{{ template "pulsar.broker.service.fqn" . }}:{{ .Values.kop.ports.plaintext }}
        - name: PULSAR_PREFIX_kafkaListeners
          value: PLAINTEXT://$(POD_NAME).{{ template "pulsar.broker.service.fqn" . }}:{{ .Values.kop.ports.plaintext }}
        {{- end }}
```

**Comment by ChenJhua** [comment]
可以了，谢谢大佬。不过有个问题。
pulsar-toolset没有kafka客户端吧。我在pulsar里面安装一个kafka client pod。
这样执行会报错
```
I have no name!@kafka-0:/$ /opt/bitnami/kafka/bin/kafka-console-producer.sh --broker-list pulsar-broker:9092 --topic kop
[2022-06-22 00:48:28,061] WARN Couldn't resolve server pulsar-broker:9092 from bootstrap.servers as DNS resolution failed for pulsar-broker (org.apache.kafka.clients.ClientUtils)
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:442)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:292)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:319)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:304)
	at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:45)
	at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:89)
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:48)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:416)
	... 5 more
```
这样执行就没有问题
```
I have no name!@kafka-0:/$ /opt/bitnami/kafka/bin/kafka-console-producer.sh --broker-list pulsar-kop-broker-0.pulsar-kop-broker.pulsar-kop.svc.cluster.local:9092 --topic kop
>1
>1
>2
>
```

**Comment by ericsyh** [comment]
pulsar-toolset 有 kafka client，但是你需要这么进入

```
kc exec -it <toolset-pod> -n <your-namespace> -c kafka -- bash
```

**Comment by ChenJhua** [comment]
好的，学到了，谢谢大佬。完美解决了我的问题

**Comment by ericsyh** [comment]
如果要用 Istio 在 K8s 外访问 KoP，建议还是用 `streamnative/sn-platform` 这个 chart，https://docs.streamnative.io/platform/v1.5.0/operator-guides/configure/istio#access-kop

**Comment by ChenJhua** [comment]
好的。我们这边应该不需要对外访问，应该不用istio。如果需要我再测试有无问题。感谢

**Comment by ChenJhua** [comment]
大佬，我这个pulsar-kop-pulsar-manager-init一直报错，看这报错应该是容器缺少了curl。你那边有这个问题吗
```
[root@master-001 ~]# kubectl logs -f pulsar-kop-pulsar-manager-init-sgrwj -n pulsar-kop
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/main: network error (check Internet connection and firewall)
WARNING: Ignoring APKINDEX.b89edf6e.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/community: network error (check Internet connection and firewall)
WARNING: Ignoring APKINDEX.737f7e01.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  curl (missing):
    required by: world[curl]
sh: curl: not found
sh: curl: not found
```
然后会出现很多init，不会关掉
```
[root@master-001 ~]# kubectl get pods -n pulsar-kop
NAME                                   READY   STATUS      RESTARTS        AGE
kafka-0                                1/1     Running     2 (7h5m ago)    7h6m
kafka-zookeeper-0                      1/1     Running     0               7h6m
pulsar-kop-alert-manager-0             2/2     Running     0               7h13m
pulsar-kop-bookie-0                    1/1     Running     0               3m6s
pulsar-kop-bookie-1                    1/1     Running     0               3m6s
pulsar-kop-bookie-2                    1/1     Running     0               3m6s
pulsar-kop-bookie-init-ckcd9           0/1     Completed   0               7h13m
pulsar-kop-broker-0                    1/1     Running     1 (7h10m ago)   7h13m
pulsar-kop-broker-1                    1/1     Running     0               7h13m
pulsar-kop-broker-2                    1/1     Running     0               7h13m
pulsar-kop-node-exporter-6bq7s         1/1     Running     0               7h13m
pulsar-kop-node-exporter-k6l5f         1/1     Running     0               7h13m
pulsar-kop-node-exporter-zt2vn         1/1     Running     0               7h13m
pulsar-kop-proxy-0                     1/1     Running     0               7h13m
pulsar-kop-proxy-1                     1/1     Running     0               7h13m
pulsar-kop-proxy-2                     1/1     Running     0               7h13m
pulsar-kop-pulsar-init-ln4gs           0/1     Completed   0               7h13m
pulsar-kop-pulsar-manager-0            1/1     Running     0               7h13m
pulsar-kop-pulsar-manager-init-484cs   0/1     Error       0               7h13m
pulsar-kop-pulsar-manager-init-7pq9k   0/1     Error       0               6h38m
pulsar-kop-pulsar-manager-init-7znhv   0/1     Error       0               7h
pulsar-kop-pulsar-manager-init-8fbj7   0/1     Error       0               6h51m
pulsar-kop-pulsar-manager-init-8rzf4   0/1     Error       0               6h47m
pulsar-kop-pulsar-manager-init-9f52j   0/1     Error       0               6h55m
pulsar-kop-pulsar-manager-init-sgrwj   0/1     Error       0               6h42m
pulsar-kop-toolset-0                   2/2     Running     0               7h13m
pulsar-kop-zookeeper-0                 1/1     Running     0               7h13m
pulsar-kop-zookeeper-1                 1/1     Running     0               7h12m
pulsar-kop-zookeeper-2                 1/1     Running     0               7h11m

```

**Comment by ericsyh** [comment]
你是离线环境里对吧，可以把这个 job 删了，随便找个有 curl 的 pod 进去，执行下 Pulsar Manager 那个初始化的命令 https://github.com/apache/pulsar-manager#access-pulsar-manager

**Comment by ChenJhua** [comment]
是离线环境，好的，我试了一下可以了。
后面可以把镜像标准化一下，提供好curl吗？
